package arytmetykaPackage;


/**
* arytmetykaPackage/DzieleniePrzezZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 6 June 2020 12:20:46 o'clock BST
*/

public final class DzieleniePrzezZero extends org.omg.CORBA.UserException
{

  public DzieleniePrzezZero ()
  {
    super(DzieleniePrzezZeroHelper.id());
  } // ctor


  public DzieleniePrzezZero (String $reason)
  {
    super(DzieleniePrzezZeroHelper.id() + "  " + $reason);
  } // ctor

} // class DzieleniePrzezZero
