package arytmetykaPackage;

/**
* arytmetykaPackage/DzieleniePrzezZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 6 June 2020 12:20:46 o'clock BST
*/

public final class DzieleniePrzezZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public arytmetykaPackage.DzieleniePrzezZero value = null;

  public DzieleniePrzezZeroHolder ()
  {
  }

  public DzieleniePrzezZeroHolder (arytmetykaPackage.DzieleniePrzezZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = arytmetykaPackage.DzieleniePrzezZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    arytmetykaPackage.DzieleniePrzezZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return arytmetykaPackage.DzieleniePrzezZeroHelper.type ();
  }

}
