
/**
* arytmetykaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 6 June 2020 12:20:46 o'clock BST
*/

public interface arytmetykaOperations 
{
  double s1 ();
  void s1 (double newS1);
  double s2 ();
  void s2 (double newS2);
  double wynik ();
  void wynik (double newWynik);
  void Suma ();
  void Roznica ();
  void Iloczyn ();
  void Iloraz () throws arytmetykaPackage.DzieleniePrzezZero;
} // interface arytmetykaOperations
