
/**
* arytmetyka.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Arytmetyka.idl
* Saturday, 6 June 2020 12:20:46 o'clock BST
*/

public interface arytmetyka extends arytmetykaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface arytmetyka
